### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Prasath",
  "email": "abc3232@gmail.com",
  "address": "TCM Nagar",
  "dateOfBirth": "2000-01-01",
  "registeredDate": "2020-04-12"
}

###